<?php

namespace IcFrontendBundle\Repository;

/**
 * IcAcreditacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcAcreditacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
