<?php

namespace IcFrontendBundle\Repository;

/**
 * IcAcreditacionQrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcAcreditacionQrRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCodigos($limite = null, $estatus, $tipo)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
				SELECT a
				FROM IcFrontendBundle:IcAcreditacionQr a
				WHERE a.estatus = :estatus
				 AND a.idAcreditacionTipo = :tipo
				')->setParameter('estatus', $estatus)->setParameter('tipo', $tipo);

        if($limite){
            $query->setMaxResults($limite);
        }

        return $query->getResult();
    }
}
