frontend_control:
    path: /tipo-control.html
    defaults: { _controller: IcFrontendBundle:Default:tipocontrol}

frontend_tipo_solicitud:
    path: /tipo-solicitud.html
    defaults: { _controller: IcFrontendBundle:Default:tiposolicitud}

frontend_solicitud_requisicion:
    path: /nueva-requisicion.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:new}

frontend_solicitud_anticipo:
    path: /nueva-solicitud-anticipo.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudAnticipo:new}

frontend_solicitud_reembolso:
    path: /nueva-solicitud-reembolso.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudReembolso:new}

frontend_solicitud_comprobacion:
    path: /nueva-solicitud-comprobacion.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudComprobacion:new}

#
# Martin Ibarra
# Rutas para reportes de solicitudes.
#

frontend_reporte_solicitud_general:
    path: /reporte-general-de-solicitudes.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudUsuario:general }

frontend_reporte_solicitud:
    path: /solicitud/{solicitud}/reporte-de-solicitud.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudUsuario:index }


frontend_inicio:
    path: /inicio.html
    defaults: { _controller: IcFrontendBundle:Default:index}

frontend_mensajes:
    path: /mensajes.html
    defaults: { _controller: IcFrontendBundle:Default:mensajes}

frontend_status:
    path: /status-solicitud.html
    defaults: { _controller: IcFrontendBundle:Default:status}

frontend_nuevo_mensaje:
    path: /nuevo-mensaje.html
    defaults: { _controller: IcFrontendBundle:Default:mensajeNuevo}

frontend_tabla_reportes:
    path: /reporte-solicitud.html
    defaults: { _controller: IcFrontendBundle:Default:reporte}

frontend_show_requisicion:
    path: /reportes.html
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:show}

frontend_acreditacion_index:
    path: /acreditacion.html
    defaults: { _controller: IcFrontendBundle:IcAcreditacion:index }

#
# Zullye Estrada
# Rutas para linea del tiempo (mensajes)
# 13 Noviembre 2017
#

#Solicitud Anticipo
frontend_enviada_anticipo:
    path: /solicitud-anticipo/enviada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_autorizada_anticipo:
    path: /solicitud-anticipo/autorizada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_rechazada_anticipo:
    path: /solicitud-anticipo/rechazada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}


##Solicitud Comprobacion
frontend_enviada_comprobacion:
    path: /solicitud-comprobacion/enviada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_autorizada_comprobacion:
    path: /solicitud-comprobacion/autorizada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_rechazada_comprobacion:
    path: /solicitud-comprobacion/rechazada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

#Solicitud Reembolso
frontend_enviada_reembolso:
    path: /solicitud-reembolso/enviada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_autorizada_reembolso:
    path: /solicitud-reembolso/autorizada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_rechazada_reembolso:
    path: /solicitud-reembolso/rechazada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

#Solicitud Requisicion

frontend_solicitud_enviada:
    path: /solicitud-requisicion/enviada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_solicitud_autorizada:
    path: /solicitud-requisicion/autorizada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

frontend_solicitud_rechazada:
    path: /solicitud-requisicion/rechazada/{token}/{estatus}
    defaults: { _controller: IcFrontendBundle:IcSolicitudRequisicion:manejoSolicitud}

#
# Ruta menu procedimientos
#

frontend_menu_procedimiento:
    path: /menu-de-procedimientos.html
    defaults: { _controller: IcFrontendBundle:Documentacion:menuprocedimiento}

frontend_documentacion_requisicion:
    path: /procedimiento-requisicion-de-compra.html
    defaults: { _controller: IcFrontendBundle:Documentacion:documentacionrequisicion}

frontend_documentacion_comprobacion:
    path: /procedimiento-comprobacion-de-gastos.html
    defaults: { _controller: IcFrontendBundle:Documentacion:documentacioncomprobacion}

frontend_documentacion_reembolso:
    path: /procedimiento-reembolso-de-compra.html
    defaults: { _controller: IcFrontendBundle:Documentacion:documentacionreembolso}

frontend_documentacion_anticipo:
    path: /procedimiento-anticipo-de-gastos.html
    defaults: { _controller: IcFrontendBundle:Documentacion:documentacionanticipo}

#
# Acreditaciones Ajax
#

frontend_ajax:
    path: /ajax-ejemplo
    defaults: { _controller: IcFrontendBundle:IcTest:ajax }