services:
#    ic_frontend.example:
#        class: IcFrontendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.jwt_auth:
        class: IcFrontendBundle\Services\JwtAuth
        arguments: ["@doctrine.orm.entity_manager"]

    app.helpers:
        class: IcFrontendBundle\Services\Helpers
        arguments: ["@app.jwt_auth"]